sonar.projectKey=flowboard-card-service
sonar.projectName=FlowBoard Card Service
sonar.host.url=http://localhost:9000
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.exclusions=**/dto/**,**/entity/**,**/exception/**,**/*Application.java,**/config/**,**/security/**,**/filter/**,**/utils/**,**/constant/**,**/constants/**,**/mapper/**,**/enums/**,**/payload/**,**/response/**,**/request/**,**/model/**,**/event/**,**/aop/**,**/scheduler/**,**/client/**,**/listener/**
sonar.java.source=21
sonar.sourceEncoding=UTF-8