sonar.projectKey=flowboard-auth-service
sonar.projectName=FlowBoard Auth Service
sonar.host.url=http://localhost:9000
sonar.token=squ_af87a29525b846d789a1c65223da7d960eb8fb41
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.exclusions=**/dto/**,**/entity/**,**/exception/**,**/*Application.java
sonar.java.source=21
sonar.sourceEncoding=UTF-8