server:
  port: 8082

spring:
  application:
    name: workspace-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://flowboard-mysql:3306/flowboard_workspace}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:flowboard-rabbitmq}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

workspace:
  invite:
    base-url: ${FRONTEND_BASE_URL:http://localhost:4200}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    display-request-duration: true
  show-actuator: false

frontend:
  base-url: ${FRONTEND_BASE_URL:http://localhost:4200}

auth:
  service:
    base-url: ${AUTH_SERVICE_BASE_URL:http://auth-service:8081/api/v1/auth}
