server:
  port: 8085

spring:
  application:
    name: card-service

  datasource:
    url: jdbc:mysql://localhost:3306/flowboard_card
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true